# Generated by Django 5.1.1 on 2026-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
