# Generated by Django 6.0.5 on 2026-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_audio_file_message_reply_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
